### PR TITLE
Store attendants log-in [feature #161078074]

### PR DESCRIPTION
**Pull request by vmuthabuku**
**What does this PR do**
This is a user log-in page for the store attendant

**Description of Task to be completed**
Have a page where Store-attendant can enter their
username and passwords and be able to
log in by clicking on the login button

**What are the relevant pivotal tracker stories**
#161078074

screenshot from 2018-10-09 10-20-20

### CODE REVIEW

**Comment by Teatoller** [comment]
Hello, Mathabuku,
You may need to use the best naming convention for your Pull Request (PR)
https://github.com/andela/bestpractices/wiki/Git-naming-conventions-and-best-practices.
Your design is looking nice!

Regards
Steven Ennis

**Comment by Arusey** [comment]
Looks great...but you might wanna reduce the size of the footer

**Comment by dev-jey** [comment]
Hi there, great work. Just don't merge your pull request to master branch.

**Comment by vmuthabuku** [comment]
> Looks great...but you might wanna reduce the size of the footer

on it

**Pull request merged**
